AdviceGenerator/Controllers/AdvicesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using AdviceGenerator.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System;


namespace AdviceGenerator.Controllers
{
  public class AdvicesController : Controller
  {
    public IActionResult Index()
    {
      var allAdvices = Advice.GetAdvices();

      return View(allAdvices);
    }
    public IActionResult Search()
    {
      return View();
    }
    [HttpPost]
    public IActionResult Search(string searchString)
    {
      return RedirectToAction("Result");
    }
    public IActionResult Result(string searchString)
    {
      try
      {
        var allAdvices = Advice.SearchAdvices(searchString);
        string quoteString = allAdvices.Contents["quotes"][0]["quote"].ToString();
        ViewBag.quoteAuthor = allAdvices.Contents["quotes"][0]["author"];
        var searchChaos = Chaos.GetChaosWord(searchString);
        string chaosString = searchChaos[0].Word.ToString();
        List<string> quoteList = quoteString.Split(" ").ToList();
        for (int i = 0; i < quoteList.Count(); i++)
        {
          if (quoteList[i].ToLower().Contains(searchString.ToLower()) || quoteList[i].ToLower() == searchString.ToLower())
          {
            quoteList.RemoveAt(i);
            quoteList.Insert(i, "um, uh " + chaosString);
          }
        }
        return View(quoteList);
      }
      catch
      {
        List<string> quoteList = new List<string> { "There", "were", "uh..", "uh", "nope,", "there", "were", "no", "results." };
        return View(quoteList);
      }
    }
  }
}

AdviceGenerator/Controllers/ChaosController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using AdviceGenerator.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using System;


namespace AdviceGenerator.Controllers
{
  public class ChaosController : Controller
  {
    public IActionResult Index()
    {
      {
        List<Chaos> chaosList = new List<Chaos>();
        int min = 0;
        var allAdvices = Advice.GetAdvices();
        string myQuote = allAdvices.Contents["quotes"][0]["quote"].ToString();
        ViewBag.quoteAuthor = allAdvices.Contents["quotes"][0]["author"];
        List<String> myOriginalWordList = myQuote.Split(" ").ToList();
        List<String> myWordList = new string(myQuote.Where(c => !char.IsPunctuation(c)).ToArray()).Split(" ").ToList();
        Double wordsToChange = Convert.ToDouble(myWordList.Count) * 0.2;
        for (int i = 0; i < wordsToChange; i++)
        {
          Random _r = new Random();
          int r = _r.Next(min, myWordList.Count - 1);
          chaosList = Chaos.GetChaosWord(myWordList[r]);
          string _chaosWord;
          if (chaosList.Count == 0)
          {
            _chaosWord = myWordList[r];
          }
          else
          {
            _chaosWord = chaosList[0].Word.ToString();
          }
          myOriginalWordList.RemoveAt(r);
          int uh = _r.Next(1, 10);
          if (uh > 4)
          {
            myOriginalWordList.Insert(r, _chaosWord);
          }
          else if (uh == 3)
          {
            myOriginalWordList.Insert(r, "uh, um " + _chaosWord);
          }
          else if (uh == 2)
          {
            myOriginalWordList.Insert(r, "uhh..." + _chaosWord);
          }
          else if (uh == 1)
          {
            myOriginalWordList.Insert(r, "uh, uh " + _chaosWord);
          }
        }
        return View(myOriginalWordList);
      }
    }
    public IActionResult Search()
    {
      return View();
    }
    [HttpPost]
    public IActionResult Search(string searchString)
    {
      return RedirectToAction("Result");
    }
    public IActionResult Result(string searchString)
    {
      try
      {
        var allAdvices = Advice.SearchAdvices(searchString);
        string quoteString = allAdvices.Contents["quotes"][0]["quote"].ToString();
        ViewBag.quoteAuthor = allAdvices.Contents["quotes"][0]["author"];
        var searchChaos = Chaos.GetChaosWord(searchString);
        string chaosString = searchChaos[0].Word.ToString();
        List<string> quoteList = quoteString.Split(" ").ToList();
        for (int i = 0; i < quoteList.Count(); i++)
        {
          if (quoteList[i].ToLower().Contains(searchString.ToLower()))
          {
            quoteList.RemoveAt(i);
            quoteList.Insert(i, "um, uh " + chaosString);
          }
        }
        return View(quoteList);
      }
      catch
      {
        List<string> quoteList = new List<string> { "There", "were", "uh", "uh", "nope", "there", "were", "no", "results" };
        return View(quoteList);
      }
    }
  }
}

AdviceGenerator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Goldblumin'</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Quando&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="../img/logo.png"
                        id="JeffOne"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advices" asp-action="Index"><img
                                    src="../img/dailyjeff.png" id="JeffOne"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advices" asp-action="Search"><img
                                    src="../img/askjeff.png" id="JeffOne"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chaos" asp-action="Index"><img
                                    src="../img/chaoticjeff.png" id="JeffOne"></a>
                        </li>
                        <li class="nav-item">
                            <a href="https://www.instagram.com/jeffgoldblum">
                                <img src="../img/morethoughts.png" id="JeffOne" style="margin-top:8px;">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class=" container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="color: #fff;">
            &copy; 2021 - Goldblumin'
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>